# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c11fa39f529970aaec1913046d04d89e44563a1713dfee2207014ff90e315f1ffdd0d8e15c68899296912bd61645c326568a707e1b5ad8e4417ee9be960b4526

test:
  secret_key_base: 59b3b7889de77d6f18478074d9cf9593df76f36a4ebfa23ced84b651ac1e21b4e1b95e9ebb8f48ed8961f1f95124ac46ee11b538ed21e45a2a7ec13c8d694fe9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
